In [23]:
#Importing Pytorch
import torch
#Importing others
import numpy as np
from __future__ import print_function

In [6]:
#Construct a 5x3 matrix, uninitialized:
x = torch.empty(5, 3)
print(x)

tensor([[-2.7203e+02,  5.9135e-43, -2.7203e+02],
        [ 5.9135e-43, -2.7198e+02,  5.9135e-43],
        [-2.7198e+02,  5.9135e-43, -2.7203e+02],
        [ 5.9135e-43, -2.7203e+02,  5.9135e-43],
        [-2.7203e+02,  5.9135e-43, -2.7203e+02]])


In [7]:
#Construct a randomly initialized matrix:
x = torch.rand(5, 3)
print(x)

tensor([[0.6587, 0.9326, 0.1850],
        [0.4988, 0.2309, 0.6182],
        [0.4954, 0.2176, 0.3011],
        [0.9952, 0.2818, 0.3852],
        [0.1242, 0.6119, 0.9174]])


In [8]:
#Construct a matrix filled zeros and of dtype long:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [9]:
#Construct a tensor directly from data:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [11]:
#Create a tensor based on an existing tensor
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print("Before: ",x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print("After: ",x)                                      # result has the same size

Before:  tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
After:  tensor([[ 1.0610, -0.7770,  0.7281],
        [-1.2007, -1.2153, -0.7877],
        [ 0.0092,  0.6554,  1.6838],
        [ 0.3015, -0.3544, -1.2286],
        [ 0.0479,  1.1737,  0.5487]])


In [12]:
#Get size of torch
print(x.size())

torch.Size([5, 3])


In [13]:
#Addition
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.1384, -0.5584,  1.4441],
        [-0.7969, -1.0248, -0.6132],
        [ 0.4838,  1.5175,  2.1574],
        [ 1.2627,  0.4370, -0.5861],
        [ 0.8079,  1.6092,  0.9844]])


In [14]:
#Another form of addition
result = torch.empty(5, 3)
#result = torch.add(x,y)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.1384, -0.5584,  1.4441],
        [-0.7969, -1.0248, -0.6132],
        [ 0.4838,  1.5175,  2.1574],
        [ 1.2627,  0.4370, -0.5861],
        [ 0.8079,  1.6092,  0.9844]])


In [15]:
#Another another form of addition
y.add_(x) # adds x to y
print(y)

tensor([[ 1.1384, -0.5584,  1.4441],
        [-0.7969, -1.0248, -0.6132],
        [ 0.4838,  1.5175,  2.1574],
        [ 1.2627,  0.4370, -0.5861],
        [ 0.8079,  1.6092,  0.9844]])


In [16]:
#Indexing
print(x[:, 1])

tensor([-0.7770, -1.2153,  0.6554, -0.3544,  1.1737])


In [17]:
#Resize or reshape tensor
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [18]:
#Get Item
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.3975])
-0.39745455980300903


In [20]:
#Converting torch tensor to a numpy array
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [22]:
#Adding 1 to the tensor value
a.add_(1)
print(a)
print(b)

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


In [24]:
#Converting Numpy to torch
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [25]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!